title: Xinlong Du
first_name: Xinlong
last_name: Du
description: Website of Xinlong Du.
lang: en
url: https://cytollen.github.io
baseurl:

markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:name/

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

sass:
  style: compressed
