title: Xinlong Du's Personal Webpage
first_name: Xinlong
last_name: Du
description: Website of Xinlong Du.
lang: en
url: https://cytollen.github.io
baseurl:

umami_website_id: a98d7c01-0c8b-44a5-a46b-4c3cdd1dc710

markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:name/

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

sass:
  style: compressed
